module.exports = {
  "storage": {
    "local": true,
    "awsS3": false,
    "digitalOcean": false
  },
  "currency": {
    "name": "INR",
    "symbol": "₹",
    "countryCode": "IN",
    "currencyCode": "INR",
    "isDefault": true
  },
  "_id": "6a3651d1b814d331437ad9a4",
  "stripePublishableKey": "",
  "stripeSecretKey": "",
  "razorPayId": "",
  "razorSecretKey": "",
  "stripeSwitch": true,
  "razorPaySwitch": true,
  "privacyPolicyLink": "https://mefigureceleb.com/privacy-policy/",
  "privacyPolicyText": "Lsvem24 Privacy Policy Original",
  "termsOfUseLink": "https://mefigureceleb.com/terms-and-conditions/",
  "termsOfUseText": "Lsvem24 Terms and Conditions Original",
  "adminCommissionOfPaidChannel": 0,
  "adminCommissionOfPaidVideo": 0,
  "durationOfShorts": 60000,
  "createdAt": "2023-08-08T12:48:46.902Z",
  "updatedAt": "2026-09-07T10:17:15.437Z",
  "minWithdrawalRequestedAmount": 10,
  "zegoAppId": "1404962986",
  "zegoAppSignIn": "0793d80b0d876d019b87523cf6237b012290f2b510c81d90f50f8eac8431fdca",
  "googlePlaySwitch": true,
  "earningPerHour": 2,
  "minSubScriber": 500,
  "minWatchTime": 3000,
  "isMonetization": true,
  "adDisplayIndex": 2,
  "flutterWaveId": "",
  "flutterWaveSwitch": true,
  "maxAdPerDay": 5,
  "minCoinForCashOut": 100,
  "commentingRewardCoins": 5,
  "likeVideoRewardCoins": 2,
  "loginRewardCoins": 100,
  "referralRewardCoins": 100,
  "requiredMembers": 5,
  "watchingVideoRewardCoins": 10,
  "minWithdrawalRequestedCoin": 0,
  "minConvertCoin": 1000,
  "isWatermarkOn": false,
  "watermarkIcon": "",
  "watermarkType": 2,
  "resendApiKey": "resendApiKey",
  "awsAccessKey": "AWS ACCESS",
  "awsBucketName": "AWS BUCKET UPDATE",
  "awsEndpoint": "AWS ENDPOIT",
  "awsHostname": "AWS HOST",
  "awsRegion": "AWS REGION",
  "awsSecretKey": "AWS SECRET KEY",
  "doAccessKey": "doAccessKey",
  "doBucketName": "doBucketName",
  "doEndpoint": "https://bucketname.region.digitaloceanspaces.com",
  "doHostname": "https://region.digitaloceanspaces.com",
  "doRegion": "doRegion",
  "doSecretKey": "doSecretKey",
  "minShortsViews": 3000000
};
