module.exports = {
  "_id": "68c2a9ff60a001bcf1ffdfed",
  "stripePublishableKey": "",
  "stripeSecretKey": "",
  "razorPayId": "",
  "razorSecretKey": "",
  "stripeSwitch": true,
  "razorPaySwitch": true,
  "privacyPolicyLink": "https://www.termsfeed.com/live/7792dfea-0768-48ea-9261-ef472318708e",
  "privacyPolicyText": "PRIVACY POLICY TEXT",
  "adminCommissionOfPaidChannel": 0,
  "adminCommissionOfPaidVideo": 0,
  "durationOfShorts": 60000,
  "createdAt": "2023-08-08T12:48:46.902Z",
  "updatedAt": "2025-06-17T12:25:23.113Z",
  "minWithdrawalRequestedAmount": 10,
  "zegoAppId": "zegoAppId",
  "zegoAppSignIn": "zegoAppSignIn",
  "googlePlaySwitch": true,
  "earningPerHour": 2,
  "minSubScriber": 1,
  "minWatchTime": 1,
  "isMonetization": true,
  "adDisplayIndex": 2,
  "currency": {
    "name": "USD",
    "symbol": "$",
    "countryCode": "USA",
    "currencyCode": "USD",
    "isDefault": true
  },
  "flutterWaveId": "FLWPUBK_TEST-cdc51a4df113a91fe33a914eaf8d1c75-X",
  "flutterWaveSwitch": true,
  "maxAdPerDay": 5,
  "minCoinForCashOut": 100,
  "commentingRewardCoins": 5,
  "likeVideoRewardCoins": 2,
  "loginRewardCoins": 100,
  "referralRewardCoins": 100,
  "requiredMembers": 5,
  "watchingVideoRewardCoins": 10,
  "minWithdrawalRequestedCoin": 0,
  "minConvertCoin": 1000,
  "isWatermarkOn": false,
  "watermarkIcon": "",
  "watermarkType": 2,
  "storage": {
    "local": true,
    "awsS3": false,
    "digitalOcean": false
  },
  "resendApiKey": "resendApiKey",
  "awsAccessKey": "AWS ACCESS",
  "awsBucketName": "AWS BUCKET UPDATE",
  "awsEndpoint": "AWS ENDPOIT",
  "awsHostname": "AWS HOST",
  "awsRegion": "AWS REGION",
  "awsSecretKey": "AWS SECRET KEY",
  "doAccessKey": "doAccessKey",
  "doBucketName": "doBucketName",
  "doEndpoint": "https://bucketname.region.digitaloceanspaces.com",
  "doHostname": "https://region.digitaloceanspaces.com",
  "doRegion": "doRegion",
  "doSecretKey": "doSecretKey"
};